version: "3.7"
services:
  # chat-app:
  #   container_name: chat-app
  #   restart: always
  #   build: .
  #   ports:
  #     - 8080
  #   links:
  #     - postgres:chat-app-database
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:latest
    container_name: chat-app-database
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}